### ISSUE TITLE
Constrained optimization during IRC?

### ISSUE THREAD

**Issue by ms860309** [eljost/pysisyphus#114]
Hi, as the title if there are any option to do this?
Maybe set the degree of freedom into 0 and let the gradient 0?
Or in mass-weighted system, let the constrained atom's mass become 10000000.

Thanks for replying,
Jianyi

**Comment by eljost** [comment]
What is you goal? Currently, IRCs are only possible in mass-weighted Cartesians. Do you want to freeze some of the Cartesians, e.g. only X and Y component of an atom or whole atoms?

**Comment by ms860309** [comment]
In some catalyst simulation, freeze the active site's H cap is more reasonable.
So, I think it is fixed whole atom, I almost done my modified version, maybe I will give a pull request later...

**Comment by eljost** [comment]
Dear Jianyi,
I'm looking forward to your PR. In recent commits on the metadyn branch I made some changes to the handling of masses in Geometry.py (see https://github.com/eljost/pysisyphus/commit/88bf6e86cf07ce908b1e1a35059b4d6705acd450#diff-abe2e82bc5bd37088147ff860e3b1147ea4d0e85f15a358ab0a8ce288e0befb9).

If you think one could get away with just setting very high  masses on some atoms, then implementing some kind of isotope-system would be the way to go, I guess. This would also benefit the integration with https://github.com/eljost/thermoanalysis, to which pysisyphus is loosely interfaced.

Or do you think that just setting a very high mass is not enough/bad idea?

**Comment by ms860309** [comment]
Thanks for your reply, I think I do not need to PR XD!!
Because my idea is to let the fixed atom mass become very large (maybe 1000000), it seems like what you have already done in this branch!!
The other approach is to remove the  degree of freedom of the fixed atom and set its gradient into 0 (What xtb constrained opt do). But in irc it is just gradient call, so maybe something wrong will happen in this approach.

Anyway your comment is very useful, thank you.
I think this issue could be closed.

**Comment by eljost** [comment]
Dear Jianyi,
I just implemented an isotope system like in Gaussian. You can request different isotopes for certain atoms, either by supplying an approximate integer mass (then an exact isotope mass will be looked up in a database) or by supplying a float, which will be directly used as mass. You can find an example [here](https://github.com/eljost/pysisyphus/tree/metadyn/examples/complex/08_hcn_deuterium_tsopt_irc)

**Comment by ms860309** [comment]
I've tried the isotopes method, I set the fixed atoms mass become 1000000000000000.0.
The result seem like normal and work pretty well.

Thanks you

**Comment by ms860309** [comment]
I think the irc procedures is like the following present.
first:
'calculate hessian'
second:
'down hill the forward and backward direction in mass-weighted'
third:
'end opt'.
First:
In orca and orca+xtb the partial hessian could help the first step. But partial hessian currently only support numerical freq.
The pysisyphus default is to use analytical freq.
`%freq
PARTIAL_Hess {22 23 24 25 26 27 28 29 30 31 32 33}
end`
Second:
The isotope with large mass can solve the second step.
Third:
I think modify `pysisyphus/intcoords/update.py` would be helpful. We can project out the hcap part during back transformation to cartesian coordinate. Here is my dirty code(Hcap is the last 12 atoms). Maybe can add this into end opt option.
Note: fragments should be false, otherwise  the index may have wrong.
` nHcap = 12
   for i in range(25):
        cart_step = Bt_inv_prim.T.dot(remaining_int_step)
        if nHcap != 0:
            cart_step[-(nHcap * 3):] = 0
        cart_rms = np.sqrt(np.mean(cart_step ** 2))`

Sorry about the messy expression.

Jianyi

**Comment by eljost** [comment]
Dear Jianyi,
to be honest, I'm a bit confused by your post. Do you propose a new feature? If so, please open a new issue where you explain what exactly you are trying to achieve.

All the best,
Johannes
