### ISSUE TITLE
Translational Invariance of Dimer Method N-vector Guess

### ISSUE THREAD

**Issue by bapride11** [eljost/pysisyphus#115]
Hello,

I'm quite new to the use of the Pisisyphus (and the Dimer method in general), but I was wondering if the initial randomly-guessed N-vector should have translational invariance. It seems like it would be a good idea in general, especially when you consider the step to escape convex regions, where:

f_tran = (-f0.dot(N))*N, where N is the normalized dimer axis

and we would like the force felt by the molecule to be translationally invariant, i.e.:

sum f_x = sum f_y = sum f_z = 0

where sum f_x means the sum over all the x components of the force vector.

It seems that otherwise the optimization based on this f_tran will literally translate the entire molecular frame as it takes a step, which "uses up" a good part of the max step if you get quite unlucky, as I have.

Taking an optimally-rotated N vector produced by the dimer code as written for my input geometry, then forcing it to be translationally invariant by subtracting the average x, y, and z components, followed by renormalization seems to considerably aid convergence.

**Comment by eljost** [comment]
Your remark seems plausible and making N translationally invariant is surely a good idea. Did you already implement it? If so, feel free to make a PR ;) Otherwise I'll try to implement it, but right now I'm quite busy.

**Comment by bapride11** [comment]
I have dirty code that could easily be formatted into a proper pull request. I'll try to put it together in the next few days (along with maybe later a new calculator I've implemented for BAGEL).

BTW: Thanks for the suggestion of DM on the ORCA forum!

Best,
Greg

**Comment by eljost** [comment]
Looking forward to it!
