### ISSUE TITLE
New feature about constrained optimization

### ISSUE THREAD

**Issue by ms860309** [eljost/pysisyphus#122]
Dear Johannes,
Sorry about let you confused. :(
What I want to achieve is to frozen some atom(I will call it Hcap in my case) in space. In previous issue, irc is in mass-weighted coordinate so we can set a isotope with large mass to achieve.
But after irc, there is an optimization of forward and backward. If i am not mistaken, this optimization is in internal coordinate.
So, there is no constrained optimization right!? Of course I can run an optimization job of `finished_first.xyz` and `finished_last.xyz` with constrained optimization in other quantum calculation software but I want to do this in pysisyphus.

Here is my thought, during back transformation from internal to cartesian, we can let the hcap atom's cart_step become zero.
Demo code:
`pysisyphus/intcoords/update.py`
```
    nHcap = 12  # The last 12 H atom.  
    for i in range(25):
        cart_step = Bt_inv_prim.T.dot(remaining_int_step)
        if nHcap != 0:
            cart_step[-(nHcap * 3):] = 0
        cart_rms = np.sqrt(np.mean(cart_step ** 2))
        # Update cartesian coordinates
        new_cart_coords += cart_step
```
I have already test this, the distance between proton is the same after optimization.
But I do not know if this modification will cause the other error?
If this work, we can add this feature into input yaml. Note that index should be considered, so maybe disable the fragment.

Jianyi

**Comment by eljost** [comment]
Dear Jianyi,
I'll try to look into it an implement atom freezing. This would be enough for now, wouldn't it? Or do you also want to constrain internal coordinates, like bond lengths?

**Comment by ms860309** [comment]
Dear Johannes,
Dihedral, angle or bond length is not what I concern.
I think freezing atom for me is pretty enough.

**Comment by eljost** [comment]
I started working on constraints here: https://github.com/eljost/pysisyphus/commit/fea2fc1ae1c06e9746d56dfd7c796ff8c1ff124c
I'll let you know when it is ready.

**Comment by eljost** [comment]
I pushed a new version to the dev-branch, where you can request constraints via YAML input. But as far as I can tell, they are not yet propagated to the endopt section. I'll tackle this in the next days. An example is found [here](https://github.com/eljost/pysisyphus/blob/dev/examples/opt/11_xtb_constrain_prims/11_xtb_constrain_prims.yaml).

**Comment by eljost** [comment]
So, I'll merge the dev branch soon. If you already want to try it out you can find an example [here](https://github.com/eljost/pysisyphus/tree/dev/examples/complex/09_hcn_iso_constrained_atom). New documentation is found [here](https://pysisyphus.readthedocs.io/en/dev/coordinate_systems.html#yaml-input).

All the best!

**Comment by ms860309** [comment]
Dear Johannes,
I will test it later and will let you know if it's work in my system.
By the way, during IRC it will call hessian calculation at the beginning. 
But I think if we didn't isotope the mass, the initial step may have slightly different?
In orca we can isotope maybe like this
```
*xyz 0 1
  C  0.35648367  0.00000000  0.14254114 
  N -0.06842070  0.00000000  1.24606543
  H  1.29729703  0.00000000  0.90815343 m=100000000000000000
*
```
Or this has just a little effect?

**Comment by eljost** [comment]
I didn't quite get your concern ... The initial displacement from the TS is also influenced by the mass and atoms with very high masses, e.g., 1.e9 amu stay basically fixed. Do you think this should be different?

**Comment by ms860309** [comment]
When we use pysisyphus with very high masses isotope, should we also isotope the mass during request orca?
Or we just need the un-isotope result then convert it into isotope-weighted by using pysisyphus.

**Comment by eljost** [comment]
Ahh, ok. Don't set the isotope mass in ORCA, only set it in pysisyphus. Everything is handled inside pysisyphus.

**Comment by ms860309** [comment]
I've tested the new version of irc with endopt.
It's seems like at least two decimal place are fixed. I think it work pretty well.

**Comment by eljost** [comment]
Ok, thanks for testing. Currently, displacements that would violate the constraints are just projected out. Peng & Schlegel noted in their 1996 paper, that sometimes, the constraints have to be reimposed by an additional, small step. This is currently not done in pysisyphus.
I'll try to add it at some point; then you'd get a more thorough compliance of the constraints.

After all, when I think about it: Did you constrain just one atom? If so, then you could also carry out your optimization without constraints and just translate the whole molecule, so your one atom is at the desired coordinates. Fixing only one atom just freezes the translational degree of freedom.

**Comment by ms860309** [comment]
Hi,
https://github.com/eljost/pysisyphus/blob/a1912fa6b53ca3805fc85a92720f0ddacb508309/pysisyphus/Geometry.py#L190
The freeze atoms is already in `**coord_kwargs` , so the line 190 would cause the error `TypeError: type object got multiple values for keyword argument 'freeze_atoms'`.
I think we can remove the freeze_atoms or remove the freeze atoms which is in the  `**coord_kwargs`.
```
            self.internal = coord_class(
                atoms,
                self.coords3d.copy(),
                **coord_kwargs,
            )
```

Jianyi

**Comment by eljost** [comment]
Dear Jianyi,

could you please provide a small example that crashes?

All the best,
Johannes

**Comment by ms860309** [comment]
Dear Johannes,
[test.zip](https://github.com/eljost/pysisyphus/files/6621903/test.zip)
Here is my input, job and the job output file.

Jianyi

**Comment by eljost** [comment]
Thanks for the example. I'll take a look and try to fix it.

**Comment by ms860309** [comment]
It's caused by the same dictionary key, the `**coord_kwargs` aleady have the freeze_atoms.
So, I think to remove the `freeze_atom=self.freeze_atoms` or modify the `**coord_kwargs` is a good solution.

**Comment by eljost** [comment]
So, lets see how this turned out. I pushed a fix to the `dev` branch. Frozen atoms are now also reported.

**Comment by ms860309** [comment]
Dear Johannes,
I had tested the fixed version of the pysisyphus and it worked pretty well.
Thank you for your assistance.

Jianyi
