### ISSUE TITLE
ONIOM Optimiser with Micro-Iterations

### ISSUE THREAD

**Issue by sheepforce** [eljost/pysisyphus#127]
Dear Johannes,
for the ongoing efforts of the integration of Pysisyphus+Spicy I will drop an issue here. While by the i-PI interface macro-iterations work properly now by traversing the whole ONIOM tree for each geometry iteration, optimising larger systems with loosely bound solvent molecules and similar stuff, will for sure require a more efficient ONIOM optimiser with micro-iterations, that traverses the ONIOM-tree from the outside to the inside. See [Geometry optimization with QM/MM, ONIOM, and other combined methods. I. Microiterations and constraints](https://onlinelibrary.wiley.com/doi/full/10.1002/jcc.10156) for an idea.

The i-PI protocol is probably not powerful enough or we would need to bend it until it's broken to support this feature directly. A first idea how both the Pysis and Spicy side could handle this without reinventing every part:

- Starting with the first geometry macro iteration, Spicy asynchronously launches one Pysisyphus instance (acting as i-PI server) per node in the ONIOM tree. Spicy will also launch one client thread per i-PI server and a strict association exists.
- Spicy will tell Pysisyphus by the YAML input file which atoms need to be fixed as they belong to deeper ONIOM (model) layers.
- Starting with the real system (the outermost layer) Pysisyphus does a constrained optimisation until convergence under constraints. The i-PI server signals convergence but keeps running and does not terminate.
- Spicy will move to the next deeper layer and start sending forces to Pysisyphus so that Pysisyphus can start optimising this next deeper layer (potentially under constraints if even deeper layers exist) until Pysis signals convergence.
- Spicy will recursively step through all ONIOM layers and optimise until each layer is converged. This criterium would be the end of the first macro iteration.
- Spicy will start the next macro iteration and again traverse the whole ONIOM tree from the outside to the inside as described above. As the geometry of the real system changed intransparently to Pysisyphus due to spicy changing the deeper layers, a geometry update message from Spicy -> Pysisyphus would be needed for each layer.

If Pysisyphus terminates after signaling convergence of forces and displacementes and convergence of the microiterations in each layer it looses the model hessian information. Spicy would also always have to restart all Pysisyphus servers after each macro-iteration. I guess this would be non-optimal. If on the other hand side Pysisyphus' i-PI servers would keep running after signaling convergence to Spicy's clients and wait for new geometries, we could take all the advantage from the history, i suppose.

There are three relevant criteria to make this work:

- Pysisyphus allows to freeze the positions of an arbitrary set of atoms in cartesian space.
- i-PI servers and Pysisyphus do not terminate after convergence
- A minor extension to the i-PI protocol would be necessary: The client is allowed to update the geometry.

I hope that this version would be the easiest and most intuitive to implement. This saves us both from the struggles to communicate which atoms are link atoms and are not free to move and so on. It also allows me to potentially optimise multicentre setups in parallel.

What do you think? :slightly_smiling_face:

**Comment by sheepforce** [comment]
[First idea of the C-API](https://gist.github.com/sheepforce/08c9d64991c2a08ef297a4814a204137) we were talking about.

**Comment by eljost** [comment]
Handled by MicroOptimizer that was merged in #146.
