### ISSUE TITLE
Freezing atoms

### ISSUE THREAD

**Issue by eljost** [eljost/pysisyphus#128]
Freezing Cartesian coordinates of certain atoms. Required for #127. Currently constraints are possible, but only in internal coordinates.

This could be realized by zeroing out any step components that would modify coordinates of frozen atoms and by removing the Cartesian force components of the frozen atoms.

I don't know if it would be useful to keep the actual forces somewhere. If the Cartesian forces of frozen atoms are zeroed, then there is no way to obtain their actual forces ...

**Comment by ms860309** [comment]
I think remove their force is okay...
At least what I see in Q-Chem or Pygsm is let the frozen atom gradient become zero and remove the step.
In pygsm:
https://github.com/ZimmermanGroup/pyGSM/blob/master/pygsm/coordinate_systems/internal_coordinates.py
```
def newCartesian:
        while True:
            microiter += 1
            Bmat = self.wilsonB(xyz1)
            Ginv = self.GInverse(xyz1)

            # Get new Cartesian coordinates
            dxyz = damp*block_matrix.dot(block_matrix.transpose(Bmat),block_matrix.dot(Ginv,dQ1))

            if self.frozen_atoms is not None:
                for a in [3*i for i in self.frozen_atoms]:
                    dxyz[a:a+3]=0.   
```
```
    def calcGrad(self, xyz, gradx):
        #q0 = self.calculate(xyz)
        Ginv = self.GInverse(xyz)
        Bmat = self.wilsonB(xyz)
      
        #with np.printoptions(threshold=np.inf):
        #    print(gradx.T)
        if self.frozen_atoms is not None:
            for a in [3*i for i in self.frozen_atoms]:
                gradx[a:a+3,0]=0.  
```

In pysisyphus:
https://github.com/eljost/pysisyphus/blob/master/pysisyphus/intcoords/update.py
```
def backtransformation:
    cart_step[frozen_atom_idx *3] = 0
```
We can do something like this.
So, I think we don't need to worry about the actual force!?

**Comment by eljost** [comment]
So, I implemented it like this on the `freeze` branch. If the CI passes I'll merge this later today.
