### ISSUE TITLE
Energy increases during the optimization

### ISSUE THREAD

**Issue by littlemoonstones** [eljost/pysisyphus#138]
## Problem
Hi, I met a problem in geometry optimization.
I tried to use BFGS to optimize the molecule, `CC1CN1C=O`.
However, during the optimization, **the energy and the maximum force gradually increased**.
I would like to know if there are any reasons for that.

## The Figure of The Optimization
![Figure_1](https://user-images.githubusercontent.com/32943414/120194095-ba602480-c24f-11eb-9b75-dc46200c5284.png)

## Environment
```bash
conda env -n pysis-env python=3.7
conda activate pysis-env
pip install pysisphus
conda install -c conda-forge openbabel
```

## Code
main.py
```python
# Limit the number of threads numpy uses
import os
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"

from pysisyphus.Geometry import Geometry
from pysisyphus.optimizers.BFGS import BFGS
from pysisyphus.calculators.OBabel import OBabel
from pysisyphus.helpers import geom_from_xyz_file

import numpy as np
from pathlib import Path

np.random.seed(0)

file_name = 'init_geometry.xyz'
coord_type = 'dlc'
try:
    geo = geom_from_xyz_file(Path(file_name), coord_type=coord_type)
    geo.set_calculator(OBabel(ff='mmff94'))
    bfgs = BFGS(geo, max_cycles=1000, thresh="gau_tight", dump=True)
    bfgs.run()
except Exception as e:
    print(e)
```

## Files
Here are my files:
[myFiles.zip](https://github.com/eljost/pysisyphus/files/6570290/myFiles.zip)
```text
myFiles.zip
├── Figure_1.png
├── final_geometry.xyz
├── init_geometry.xyz
├── internal_coords.log
├── main.py
├── optimization.h5
├── optimization.trj
├── optimizer.log
└── pysisyphus
```

**Comment by eljost** [comment]
Dear littlemoonstones,
thanks for this comprehensive issue description! I'll try to take a closer look at it. As a first guess: with the BFGS-optimizer the Hessian is used as is in the step calculation, so there is no eigenvalue shift. Please see [10.1063/1.1515483](https://aip.scitation.org/doi/pdf/10.1063/1.1515483) Section .IV A - D. Maybe the (updated) Hessian has a negative eigenvalue, resulting in uphill steps...

Try to use RFOptimizer; there appropriate shifts are determined. Is there a reason for you to use BFGS? Regarding molecular optimizations RFOptimizer is the most robust optimizer.

All the best,
Johannes

**Comment by littlemoonstones** [comment]
Dear Johannes,
thanks for your suggestions. I will try to use RFOptimizer.

The reason I choose BFGS is that I want to enhance the ability of BFGS in geometry optimization by machine learning.

Regards,
littlemoonstones

**Comment by eljost** [comment]
Ok. But then it must be assured that the Hessian remains positive-definite. Pysisyphus also supports a double damped BFGS update. Maybe take a look at that.
```
bfgs = BFGS(geo, max_cycles=1000, thresh="gau_tight", dump=True, update="double")
```

See also:
https://github.com/eljost/pysisyphus/blob/2fe4f11ce4ad90d387ac7b3ce908cf393a5bed01/pysisyphus/optimizers/BFGS.py#L46

**Comment by eljost** [comment]
Hmm, I just ran your example locally using the latest `nixtest` branch and it converges fine ...

[obabel_bfgs.zip](https://github.com/eljost/pysisyphus/files/6574599/obabel_bfgs.zip)

I plan on doing a new release soon.

**Comment by littlemoonstones** [comment]
Thanks!!! After added `update="double"`, it works!!
