### ISSUE TITLE
Test: BFGS has little impact if changing the directions of forces

### ISSUE THREAD

**Issue by littlemoonstones** [eljost/pysisyphus#145]
## Question
Hi, I did a test that reverses forces direction, meaning that I insert the minus sign before forces, like `-forces`. So in the process of optimization, the geometry would expectedly diverge. However, I used BFGS with `update="bfgs"`, and it **unexpectedly** converged as fig.(d) shows. That's strange! Because the forces were turned into the opposite direction, the results theoretically should be divergence instead of convergence. Therefore, I wonder why the direction of the force barely impacts on `update=bfgs`.

## Environment
```bash
conda env -n pysis-env python=3.7
conda activate pysis-env
conda install -c conda-forge openbabel
```
## Files
[force-direction.zip](https://github.com/eljost/pysisyphus/files/6603662/force-direction.zip)

### OBabel.py
https://github.com/eljost/pysisyphus/blob/0f9a4624a5a226196b7a5ae2802910316a8258b6/pysisyphus/calculators/OBabel.py#L77
Insert the minus sign, and the directions of forces become opposite.
```python
results = {"energy": energy, "forces": -forces} 
```
### main.py
```python
# Limit the number of threads numpy uses
import os
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"

from pysisyphus.Geometry import Geometry
from pysisyphus.optimizers.BFGS import BFGS
from pysisyphus.optimizers.RFOptimizer import RFOptimizer
from pysisyphus.calculators.OBabel import OBabel
from pysisyphus.helpers import geom_from_xyz_file

import numpy as np
from pathlib import Path

np.random.seed(0)

file_name = 'init_geometry.xyz'
coord_type = 'cart'

try:
    path = Path(file_name)
    geo = geom_from_xyz_file(path, coord_type)
    geo.set_calculator(OBabel(ff='mmff94'))
    # Choose one optimizer
    optimizer = RFOptimizer(geo, max_cycles=500, thresh="gau", dump=True)
    # optimizer = BFGS(geo, max_cycles=500, thresh="gau", dump=True, update="bfgs")
    # optimizer = BFGS(geo, max_cycles=500, thresh="gau", dump=True, update="damped")
    # optimizer = BFGS(geo, max_cycles=500, thresh="gau", dump=True, update="double")
    optimizer.run()
except Exception as e:
    print(e)
```
### BFGS
![BFGS](https://user-images.githubusercontent.com/32943414/120912968-22868e80-c6c6-11eb-9b35-f8df8fbc9e4b.jpg)

### RFOptimizer
![RFOptimizer](https://user-images.githubusercontent.com/32943414/120912972-24e8e880-c6c6-11eb-8009-ec3aca367612.jpg)

**Comment by eljost** [comment]
Hi,
I guess it's probably the same answer as to #138. The sign of some eigenvalue changes during the optimization, thus reversing the sign of the negative force in the step calculation (again). Lucky error cancellation. This explanation is also consistent with the failing optimizations for the damped BFGS updates, as they try to preserve the positive eigenvalue-structure of the Hessian, thus no (error-cancelling) sign-reversal is observed. Similar thing for RFO. Here the Hessian is explicitly shifted to avoid the (error-cancelling) sign-change.

All the best,
Johannes
