### ISSUE TITLE
Export pysisplot results to CSV file

### ISSUE THREAD

**Issue by tanoury1** [eljost/pysisyphus#151]
Hi,
I've been trying to find a way to export the results from pysisplot to a CSV file for further plotting with other software packages.  Is there an easy way to do this with Julia?

Thank you,
Jerry

**Comment by eljost** [comment]
Dear Jerry,
in what type of data are you interested? Most of the results that can be displayed via `pysisplot` are read from HDF5 files, which should easily be accessible from Julia, e.g. [HDF5.jl](https://github.com/JuliaIO/HDF5.jl).

**Comment by tanoury1** [comment]
Hi Johannes,
I'm interested in the energy vs. IRC length plot generated
from finished_irc_data.h5.  I was trying to access the data using the hdf5
utilities in Julia, but kept running into problems.  I thought you might
already have something scripted.

Jerry

**Comment by eljost** [comment]
Dear Jerry,
assuming that h5py produces valid HDF5 files and your Julia library can read valid HDF5 files it should work somehow ...
Nonetheless, please try the attached script ([dumpirc.txt](https://github.com/eljost/pysisyphus/files/6795212/dumpirc.txt), rename it from .txt to .py). Use it as:
```bash
# python dumpirc.py [hdf5 file]
python dumpirc.py finished_irc_data.h5
```

This should give you three columns: reaction coordinate w.r.t. the first point; reaction coordinate w.r.t to the TS and the electronic energy in the last column; everything in atomic units.

Please let me know if this helped you/solved the problem.

All the best,
Johannes

**Comment by tanoury1** [comment]
Hi Johannes,
Thank you for the script!

Jerry
