### ISSUE TITLE
Convert cartesian to internal coordinate

### ISSUE THREAD

**Issue by Amingeo** [eljost/pysisyphus#152]
Dear developers,
thanks for the interesting code.
I am wondering, would it be possible to provide an script with which pysisyphus reads a given file containing molecule geometry (e.g. as xxx.xyz or xxx.pdb , xxx.zmat or any other format which is easy to handle for the code) and prints the B matrix it calculates for it in another file?
Kind regard,
Amin

**Comment by eljost** [comment]
Dear Amin,

do you require pysisyphus to use a certain topology that you provide? Or would you be fine with the coordinates that are automatically setup by pysisyphus?

All the best,
Johannes

**Comment by eljost** [comment]
Try this: [printB.py](https://gist.github.com/eljost/e99f9c059f38ad9d93977cdffb379e00)

Please let me know if this solves your problem.

**Comment by Amingeo** [comment]
> 
> 
> Dear Amin,
> 
> do you require pysisyphus to use a certain topology that you provide? Or would you be fine with the coordinates that are automatically setup by pysisyphus?
> 
> All the best,
> Johannes

Dear Johannes,
thanks a lot for your prompt consideration. I need pysisyphus  reads a certain topology ( in any format like z matrix or pdb or other common formats).
Thanks a again, 
Amin

**Comment by Amingeo** [comment]
> 
> 
> Try this: [printB.py](https://gist.github.com/eljost/e99f9c059f38ad9d93977cdffb379e00)
> 
> Please let me know if this solves your problem.

Dear Johannes,
seems to be the one I am looking for, many thanks.
Just a question, this input topology here should be xyz or something else?
Best regards,
Amin

**Comment by eljost** [comment]
XYZ does not store any topology, pysisyphus figures it out on its own. With the provided script you can't provide any toplogy, but it certainly could be added. What type of coordinates do you nead? Are bonds, bends and dihedrals enough?

**Comment by Amingeo** [comment]
> 
> 
> XYZ does not store any topology, pysisyphus figures it out on its own. With the provided script you can't provide any toplogy, but it certainly could be added. What type of coordinates do you nead? Are bonds, bends and dihedrals enough?

What I am looking for is the so called Wilson B-Matrix which can be used to convert xyz cartesian coordinates to a corresponding set of internal coordinates ( by multiply its inverse B^-1 to xyz matrix) and also to convert the Cartesian forces to the same internals via multiplying by transpose of B^-1 .

I can provide input Cartesian structure in any conventional molecular format. Do you think pysisyphus can handle that?
