### ISSUE TITLE
Turbomole parser crashes if gradient contains more than one cycle

### ISSUE THREAD

**Issue by mkrompiec** [eljost/pysisyphus#19]
this is my gradient file:
$grad          cartesian gradients
  cycle =      1    SCF energy =      -78.5469489756   |dE/dxyz| =  0.011084
   -1.24343979543875      0.00000000000000      0.00000000000000      c
    1.24343979543875      0.00000000000000      0.00000000000000      c
   -2.32247341731646      1.72531995932459      0.00000000000000      h
   -2.32247341731646     -1.72531995932459      0.00000000000000      h
    2.32247341731646      1.72531995932459      0.00000000000000      h
    2.32247341731646     -1.72531995932459      0.00000000000000      h
  0.54206405236883D-02  0.77493567118836D-13  -.56657581255684D-13
  -.54206405234827D-02  -.12123635428907D-12  -.10562291294545D-13
  0.18253704797031D-02  -.35625085610502D-02  0.11830936875874D-13
  0.18253704796780D-02  0.35625085610698D-02  0.19393071175979D-13
  -.18253704797327D-02  -.35625085610979D-02  0.00000000000000D+00
  -.18253704797391D-02  0.35625085610707D-02  0.00000000000000D+00
  cycle =      2    SCF energy =      -78.5471031456   |dE/dxyz| =  0.000390
   -1.25064626604651     -0.00156469323803      0.00000000000000      c
    1.25064626604651     -0.00156469323803      0.00000000000000      c
   -2.32795154440308      1.73774490864832      0.00000000000000      h
   -2.33549344139942     -1.73618021541029      0.00000000000000      h
    2.32795154440308      1.73774490864832      0.00000000000000      h
    2.33549344139942     -1.73618021541029      0.00000000000000      h
  0.95929134047879D-04  -.88092601660650D-04  0.16333203403010D-13
  -.95929134413808D-04  -.88092601486789D-04  -.31177819748840D-13
  -.18513340706239D-04  0.68376385047308D-05  0.38661100509657D-13
  -.22803021622431D-03  0.81388166587537D-04  0.39119745143396D-13
  0.18513340650825D-04  0.68376385558566D-05  0.00000000000000D+00
  0.22803021631757D-03  0.81388166594198D-04  0.18803139539624D-13
$end

And this is the corresponding error:
pyparsing.ParseException: Expected "$end", found 'c'  (at char 948), (line:15, col:3)
This means that gradient files from a geometry optimization will always crash the parser.

**Comment by eljost** [comment]
I'll take a look into it.

**Comment by eljost** [comment]
Dear @mkrompiec, is this issue solved for you?

**Comment by mkrompiec** [comment]
Thank you!
