### ISSUE TITLE
NEB error with Gaussian calculator

### ISSUE THREAD

**Issue by Kr0n0ss** [eljost/pysisyphus#193]
Hi,
While running NEB with the gaussian calculator I got the following error:
TypeError: __init__() missing 1 required positional argument: 'route'
And I'm not sure what it refers to or how to fix it.
Any ideas?

Many thanks,
David

P.S: This is the YAML input file

geom:
 type: cart
 fn: reactant_product.trj
calc:
 type: g16
 keywords: ub3lyp/def2svp scrf=(cpcm,solvent=acetonitrile) empiricaldispersion=gd3 gfinput gfprint scf=(maxcycle=1200,yqc)
 charge: 2
 mult: 3
 pal: 32
 mem: 2000
preopt:
 max_cycles: 500
interpol:                       # In NEBs the whole path is interpolated beforehand.
 type: redund                   # Possible values: redund|idpp|lst|linear
 between: 10                    # Interpolate n-geometries between every pair of supplied
                                # geometries. For two this yields 1 + 10 + 1 == 12 images,
                                # for three geometries this yields 1 + 10 + 1 + 10 + 1 == 23
                                # geometries.
cos:
 type: neb
 climb: True
 fix_ends: True
opt:
 type: lbfgs
 align: True
 rms_force: 0.01
 max_step: 0.04
tsopt:
 type: rsirfo
 do_hess: True
 max_cycles: 500
 hessian_recalc: 7
irc:
 type: eulerpc
 rms_grad_thresh: 0.0005

**Comment by Kr0n0ss** [comment]
Thanks, that fixed the error. However, now I'm getting the following one:
Failed to load key 'formchk_cmd' from section 'gaussian16'. Exiting!

My .pysisyphusrc file already has inside:
[gaussian16]
# Cmds to execute. Please ensure that the binaries are found in your $PATH.
cmd=g16
formchk=formchk
unfchk=unfchk
rwfdump=rwfdump

Btw, I'm using v0.7.2 .

thanks.

**Comment by eljost** [comment]
Please update to the latest version 0.7.5: `python -m pip install --upgrade pysisyphus`. Please see the deprecations section [here](https://github.com/eljost/pysisyphus/releases/tag/0.7.5). If you use the latest version and the respective binaries are on your $PATH you don't have to add them to `.pysisyphusrc` at all.

**Comment by Kr0n0ss** [comment]
Seems to be running now. Many thanks!

**Comment by Kr0n0ss** [comment]
Is it possible to have different convergence thresholds for the images and the Climbing Image in NEB?

**Comment by eljost** [comment]
This is not implemented. The NEB convergence is checked as "whole". By providing the `rms_force` and `rms_force_only` arguments to the [Optimizer](https://pysisyphus.readthedocs.io/en/master/api/pysisyphus.optimizers.html#module-pysisyphus.optimizers.Optimizer) you can force pysisyphus to signal convergence by checking on the rms(forces) and neglecting max(forces)/max(step)/rms(step). Right now this is not really documented. I'll add the relevant documentation later this day.

**Comment by eljost** [comment]
Given the fact that such kind of convergence check could be implemented, what do you have in mind? I guess a tighter convergence on the CI?

**Comment by Kr0n0ss** [comment]
Yes, exactly that. Seems to be a good approach, at least from my experience so far with ORCA.
Thanks!!

**Comment by Kr0n0ss** [comment]
Also, I know this is not essential, but given the fact that your plots are quite nice, I was wondering if they could also be given in kcal/mol instead of just kj/mol .

**Comment by eljost** [comment]
Which plots do you mean? The `--cosens` and `--cosforces` plots? Personally, I'm not too keen on calories because they are not SI units. I'll try to see if I can make it happen though.

**Comment by Kr0n0ss** [comment]
Those and also the IRC path. I know the issue with the kcal/mol units, but they are quite common when reporting reaction mechanisms, etc. But I know this is probably not a priority ^^. 
If you make any updates including them, please let me know, I would be very eager to use them :)
Thanks

**Comment by eljost** [comment]
In my (humble) opinion it shouldn't even be allowed to report barrier heights in kcal mol⁻¹ instead of kJ mol⁻¹ in papers ;) But I'm not 100% percent sure that I never did it though ...

**Comment by Kr0n0ss** [comment]
I agree it's a matter of discussion. And even in benchmarking papers, this is the unit for talking about "chemical accuracy".
On a different matter, are there any plans to implement an optimizer for MECP? I saw you recently added one for conical intersections, so the idea crossed my mind. This is currently implemented in ORCA but other popular software lack of 
 this (turbomole, gaussian). Of course, I'm bringing this up because is another thing I quite often use ^^.

**Comment by Kr0n0ss** [comment]
Hi,
When running NEB to a file with .xyz of the merged reactant and product, it fails to initialize properly, only works when using .trj file. Is there any special reason for that?
Thanks

**Comment by Kr0n0ss** [comment]
Also, are the NEB cycles dumped in a trajectory file? So that one can use those geometries and energies to make an alternative plot to that in pysisplot
Many thanks!

**Comment by eljost** [comment]
You can find the geomtries of the respective cycle in the cycle_XXX.trj file. Everything is also dumped to the HDF5 file optimization.h5. If you have the HDF5 tools available you can list the contents of the file by
```bash
h5ls optimization.h5
```
It should contain one or more groups. You can then proceed to further inspect it by executing
```bash
h5ls optimization.h5/[group]
```

There you can find all required quantities in a machine readable form.
