### ISSUE TITLE
Read binary CI vector file from ORCA

### ISSUE THREAD

**Issue by LeiTong-NJU** [eljost/pysisyphus#233]
Hi,

After perfoming a Spin-Flip CIS calculation in ORCA, how could I directly obtain the CI eigenvectors from the 'job.cis' file?
I read the code of  parse_orca_cis() function, but when I typed
''cis_fn = "D:/python/tetracene_udft.cis
MO = parse_orca_cis(cis_fn)''
It turned out an error "unpack requires a buffer of 284704 bytes"
How to fix this problem? 

Thanks

**Comment by eljost** [comment]
I just released a [new version](https://pypi.org/project/pysisyphus/0.8.0a0/) . Please try it out and check if everything works now, as intended.

```bash
pip install pysisyphus==0.8.0a0
```

**Comment by LeiTong-NJU** [comment]
Dear Johannes,

Thank you very much. I will update the pysisyphhus and try it.

**Comment by LeiTong-NJU** [comment]
Dear Johannes,Thank you for your reply. I will try it.

Best regards
 
Lei Tong
 
Nanjing University, China

&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Dec 17, 2022 05:23 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [eljost/pysisyphus] Read binary CI vector file from ORCA (Issue #233)

&nbsp;



 
I just released a new version . Please try it out and check if everything works now, as intended.
 pip install pysisyphus==0.8.0a0

**Comment by LeiTong-NJU** [comment]
Dear Hohannes,
I have already installed pysisyphus==0.8.0a0, but it reported the same mistake，

The commands:
import struct
from pysisyphus.calculators.ORCA import parse_orca_cis
cis_fn='/fsa/home/mx_tonglei/statistic/ORCA/test/tetracene_udft.cis'
MOS=parse_orca_cis(cis_fn)

The results:
  File "test.py", line 4, in <module>
    MOS=parse_orca_cis(cis_fn)
  File "/fsa/home/mx_tonglei/anaconda3/lib/python3.8/site-packages/pysisyphus/calculators/ORCA.py", line 207, in parse_orca_cis
    coeffs_b = parse_coeffs(b_lenci, b_frozen, b_occupied, b_virtual)
  File "/fsa/home/mx_tonglei/anaconda3/lib/python3.8/site-packages/pysisyphus/calculators/ORCA.py", line 148, in parse_coeffs
    coeffs = struct.unpack(lenci * "d", cis_handle.read(lenci * 8))
struct.error: unpack requires a buffer of 284704 bytes

Should I perfrom SF-CIS calculation in pysisyphus linked wo ORCA?

**Comment by eljost** [comment]
Good to know. Personally, I never did/tried SF calculations. Can you please provide an example input, that reproduces to problem?

**Comment by LeiTong-NJU** [comment]
[tetracene.txt](https://github.com/eljost/pysisyphus/files/10277146/tetracene.txt)
This was the SF-TDDFT(Sorry, I miswrote it as SF-CIS before) input file I performed in the ORCA.. After the calculation, I wanted to directly obtain the CI eigenvectors from the 'tetracene.cis' file.

**Comment by eljost** [comment]
The `dev` branch now implements parsing these calculations. They are not properly handled in the rest of the code though... A warnings is also printed. Personally, handling SF calculations in the OverlapCalculator would be nice but it is not very high on my TODO list.

Let me know if this fixes your issue for now.

All the best
Johannes

**Comment by LeiTong-NJU** [comment]
Dear Johannes,
Thank you for your generous help, the dev branch fixed my problem. The issue could be closed.

Best regards
Lei
