### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by kleflick** [eljost/pysisyphus#262]
Hi,
I get an error when I try to optimize the transition state like in your example  01_biaryl_xtb_tsopt_recalc.yaml.
xtb is working fine as stand-alone but I get 
FileNOtFoundError: [Errorno 2] No such file or directory:
/tmp/calculator_000_000...../hessian.

I think something is wrong in my environment. I use ubuntu under wsl, miniconda3 with Python3.9.
Thank you very much
Klemens

**Comment by eljost** [comment]
Dear Klemens,

can you please post your `$HOME/.pysisyphusrc`?

When the calculation crashes, there should be a directory like `crashed_calculator_000`. Please have a look at the files there. Do they tell you something? Did the XTB calculation converge and is the `hessian` file there?
