### ISSUE TITLE
Support for SE-GSM?

### ISSUE THREAD

**Issue by mhyeok1** [eljost/pysisyphus#267]
Hello!

I cannot find an example of the single-ended growing string method in pysisyphus.

Am I just missing something or is it not implemented yet?

Best regards.

**Comment by eljost** [comment]
Dear mhyeok1,

SE-GSM is not implemented, but (Growing) Newton Trajectories are. But right now they are not available via YAML and not documented. Associated tests are found [here](https://github.com/eljost/pysisyphus/blob/master/tests/test_growingnt/test_growingnt.py). If you are interested in using this please let me know.
