### ISSUE TITLE
thermo module 'QCData' is not defined

### ISSUE THREAD

**Issue by sespic** [eljost/pysisyphus#286]
Running pysisthermo on any hessian.h5 file returns the following error: 

line 30, in run_thermo: thermo = get_thermoanalysis_from_hess_h5(hess_h5, T=T, p=p, point_group=point_group)
line 37, in get_thermoanalysis_from_hess_h5: qcd = QCData(thermo_dict, point_group=point_group)
NameError: name 'QCData' is not defined

 - OS: Linux
 - Python version: 3.10.8

pysisyphus was installed with pip in an conda environment.

**Comment by eljost** [comment]
The optional `thermoanalysis` package is missing. I added a check/note regarding this package on the current `dev` branch. Currently, you can fix this by installing it, e.g. via

```
python -m pip install git+https://github.com/eljost/thermoanalysis
```

**Comment by sespic** [comment]
Thanks for the quick reply, it works perfectly!!!
