### ISSUE TITLE
IRC@yaml

### ISSUE THREAD

**Issue by chburger** [eljost/pysisyphus#50]
Maybe I am missng something but I am correct that IRC calculations do not work not with yaml
input files? If they do.. could you pls provide an example? (I am not too much into python yet)

Thanks so much for providing the program & all your efforts !

**Comment by eljost** [comment]
Hi,
of course it's possible. I added two examples here: [yaml IRC examples](https://github.com/eljost/pysisyphus/tree/dev/examples/irc) in the `dev` branch. After the CI finishes I'll merge everything in the `master` branch and it work (hopefully ;)).

If you have any problems feel free to open an issue. A more thorough documentation effort is underway.

**Comment by chburger** [comment]
Thanks so much! That looks pretty much what I had tried myself.. But  
that was for Turbomole, for which I am not sure whether hessians can  
be read by pysisphus.

Best wishes

Peter

  eljost <notifications@github.com> schrieb/wrote::

> Hi,
> of course it's possible. I added two examples here: [yaml IRC  
> examples](https://github.com/eljost/pysisyphus/tree/dev/examples/irc) in the  
> `dev` branch. After the CI finishes I'll merge everything in the  
> `master` branch and it work (hopefully ;)).
>
> If you have any problems feel free to open an issue. A more thorough  
> documentation effort is underway.

**Comment by eljost** [comment]
As this is on my TODO list anyway I'll try to implement hessians for TURBOMOLE...

**Comment by eljost** [comment]
What method do you want to use for the hessian calculation? DFT or HF? Or some ricc2 method with NumForce? I added DFT/HF  hessian with aoforce to the turbo_hess branch and will it merge soon.

Does this help?
